import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/NotoSans-Variable.ttf",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/NotoSans-Variable.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "다행 - 행사의 설계도를 만들다",
  description: "Generated by create next app",
  icons: {
    icon: "/dahaeng_icon/icon_main_square.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
